spring:
  application:
    name: fan-signal-api
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fan-signal
      username: master
      password: master
      authentication-database: admin